### ISSUE TITLE
Some suggestions 

### ISSUE THREAD

**Issue by ipranjal** [3scava1i3r/HackAtom-V#2]
1) lake of using non and directly managing the packages bother me as it will cause issues while updating dependencies 

2) I would really love to see support for typescript as I rely lot on the text editor auto complete feature with does not work that well with basic JavaScript 

3) Any plans for Electron wrapper in future ?

**Comment by 3scava1i3r** [comment]
- With lack of time I had to directly manage the packages, will change it asap 
- I will try best to add typescript support but I can't guarantee it 
- no plans for electron wrapper right now

**Comment by ipranjal** [comment]
@3scava1i3r i have an imp work next few days , I’ll work on typescript support 

Are planning to use yarn or npm for dependencies ? 

Also I am planning to improve the GUI framework for this project

**Comment by 3scava1i3r** [comment]
I am really pleased with your interest but this is my beginner project so I wish to work on it alone, learn by the improving the same.
