### ISSUE TITLE
Suggestion: functionality 

### ISSUE THREAD

**Issue by ipranjal** [3scava1i3r/HackAtom-V#3]
1) While this advertise to be a decentralised memory / file sharing system it really doesn’t store meta related  with file , memories only make sense while it has sensible meta data associated with it 

2) Any plan for implementing private sharing via user with system ?

**Comment by 3scava1i3r** [comment]
For the second point I am looking forward to working on the same after the results and for the first point we are saving image/gif buffer data on skynet and then passing its skylink on the personal ethermint node

**Comment by ipranjal** [comment]
> For the second point I am looking forward to working on the same after the results and for the first point we are saving image/gif buffer data on skynet and then passing its skylink on the personal ethermint node

My whole point is , it does not have imp meta details as user , description etc
